---
apiVersion: v1
kind: Secret
metadata:
  name: storage-auth
  namespace: browsers
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "{{ .Values.storage.access_key }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.storage.secret_key }}"
  AWS_ENDPOINT: "{{ .Values.storage.api_endpoint }}"
  STORAGE_PREFIX: "{{ .Values.storage.storage_prefix }}"
  MC_HOST: "https://{{ .Values.storage.access_key }}:{{ .Values.storage.secret_key }}@{{ .Values.storage.api_endpoint }}"
  ACL: "{{ .Values.storage.acl }}"

---
apiVersion: v1
kind: Secret
metadata:
  name: storage-auth
  namespace: default
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "{{ .Values.storage.access_key }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.storage.secret_key }}"
  AWS_ENDPOINT: "{{ .Values.storage.api_endpoint }}"
  STORAGE_PREFIX: "{{ .Values.storage.storage_prefix }}"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config

data:
  BROWSER: {{ .Values.browser }}
  ACCESS_PREFIX: {{ .Values.storage.access_prefix }}
  STORAGE_PREFIX: {{ .Values.storage.storage_prefix }}
  PROFILE_URL: "{{ .Values.profile_url | default "" }}"
  JOB_CLEANUP_INTERVAL: "{{ .Values.job_cleanup_interval }}"

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cleanup
  namespace: default
spec:
  schedule: "*/30 * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: cleanup
            image: ikreymer/permaproof-main
            imagePullPolicy: Always
            command: ["python", "cleanup.py"]
            envFrom:
              - secretRef:
                  name: storage-auth

              - configMapRef:
                  name: {{ .Values.name }}-config


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: perma-fact-{{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: perma-fact-{{ .Values.name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: perma-fact-{{ .Values.name }}

    spec:     
      containers:
        - name: main
          image: ikreymer/permaproof-main
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: {{ .Values.name }}-config

            - secretRef:
                name: storage-auth

---

apiVersion: v1
kind: Service

metadata:
  name: perma-fact-{{ .Values.name }}
  labels:
    app: perma-fact-{{ .Values.name }}

{{- if .Values.service }}
  {{- if .Values.service.annotations }}
  annotations:
  {{- range $key, $val := .Values.service.annotations }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
{{- end }}

spec:
  selector:
    app: perma-fact-{{ .Values.name }}

{{- if .Values.service }}
  {{- if .Values.service.type }}
  type: {{ .Values.service.type | quote }}
  {{- end }}
{{- end }}

  ports:
    - protocol: TCP
      port: 80
      name: main


